name: pre-commit checks

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up Python environment
      run: |
        pip install pipenv pre-commit
        pipenv install --dev

    - name: Run pre-commit
      run: pre-commit run --show-diff-on-failure --color=always --all-files
